name: Pkgdown

on:
  push:
    branches:
      - main
jobs:
  pkgdown:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages("remotes")'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'
      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site()'
      - name: Deploy to GitHub Pages
        run: Rscript -e 'pkgdown::deploy_to_branch()'
